---
title: "R Notebook"
output: html_notebook
---

```{r}
library(cutpointr)
library(tidyverse)

#read in combined file
meta <- read_tsv("../../../analyses/add-histologies/output/ALT PBTA oct 2021 (including all plates)-updated-hist-alt.tsv",
         guess_max = 1000)

#subset for HGG and non-HGG
hgat <- meta %>%
  filter(group == "HGAT")
non_hgat <- meta %>%
  filter(group == "non-HGAT")

#how many per group?
meta %>%
  group_by(group, phenotype) %>%
  tally()
```

#run optimal cutpoint by group
```{r}
# remove NA becuase those were being counted as negatives
meta <- meta %>%
  filter(!is.na(phenotype))

#how many per group?
meta %>%
  group_by(group, phenotype) %>%
  tally()

opt_cut <- cutpointr(meta, telomere_ratio, phenotype, group, metric = sum_sens_spec, 
                     tol_metric = 0.05, break_ties = c, na.rm = T)
summary(opt_cut)
```

#plot by group
```{r}
plot_metric(opt_cut)
#save as PDF
pdf("../../../analyses/cutpoint-analysis/plots/all-pbta-by-subgroup.pdf", height = 4, width = 6, onefile=FALSE)
plot_metric(opt_cut)
invisible(dev.off())
```
#subset and plot - HGAT
```{r}
opt_cut %>%
  filter(subgroup == "HGAT") %>%
  select(optimal_cutpoint, sum_sens_spec) %>% 
  unnest(cols = c(optimal_cutpoint, sum_sens_spec)) %>%
  arrange(-sum_sens_spec)
```

#subset and plot - non-HGAT
```{r}
opt_cut %>%
  filter(subgroup == "non-HGAT") %>%
  select(optimal_cutpoint, sum_sens_spec) %>% 
  unnest(cols = c(optimal_cutpoint, sum_sens_spec)) %>%
  arrange(-sum_sens_spec)
```

#all samples together - cutpoint
```{r}
cp <- cutpointr(meta, telomere_ratio, phenotype, 
                method = maximize_metric, metric = sum_sens_spec, na.rm = T)
summary(cp)
```
# all samples together - plot
```{r}
plot(cp)
pdf("../../../analyses/cutpoint-analysis/plots/all-pbta.pdf", height = 4, width = 8, onefile=FALSE)
plot(cp)
invisible(dev.off())
```
#hgat alone - cutpoint
```{r}
cp <- cutpointr(hgat, telomere_ratio, phenotype,
                method = maximize_metric, metric = sum_sens_spec, na.rm = T)
summary(cp)
```

#hgat alone - plot
```{r}
plot(cp)
pdf("../../../analyses/cutpoint-analysis/plots/hgat.pdf", height = 4, width = 8, onefile=FALSE)
plot(cp)
invisible(dev.off())
```

#non-hgat alone cutpoint
```{r}
cp <- cutpointr(non_hgat, telomere_ratio, phenotype, 
                method = maximize_metric, metric = sum_sens_spec, na.rm = T)
summary(cp)
```

#non-hgat alone plot
```{r}
plot(cp)
pdf("../../../analyses/cutpoint-analysis/plots/non-hgat.pdf", height = 4, width = 8, onefile=FALSE)
plot(cp)
invisible(dev.off())
```