---
title: "R Notebook"
output: html_notebook
---

```{r}
library(cutpointr)
library(tidyverse)
library(ggpubr)

# define directories 
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
analysis_dir <- file.path(root_dir, "analyses", "04-cutpoint-analysis")
input_dir <- file.path(root_dir, "analyses", "02-add-histologies", "output")
output_dir <- file.path(analysis_dir, "output")

source(file.path(analysis_dir, "code", "theme.R"))
       
#read in combined file
meta <- read_tsv(file.path(input_dir, "stundon_hgat_updated_hist_alt.tsv"),
         guess_max = 1000) %>%
  mutate(alt_final = toupper(`alt final`))

#subset for HGG and non-HGG
hgat <- meta %>%
  filter(group == "HGAT")
 non_hgat <- meta %>%
   filter(group == "non-HGAT")

#how many per group?
meta %>%
  group_by(group, alt_final) %>%
  tally()
```
# Shuffle telhunter ratios and plot ROC
```{r shuffle telhunter ratios, fig.height=4, fig.width=8}
set.seed(2022)
meta <- meta %>%
  mutate(shuffled_telhunt = sample(telomere_ratio))

opt_cut <- cutpointr(meta, shuffled_telhunt, alt_final,
                method = maximize_metric, metric = sum_sens_spec, na.rm = T)

# plot shuffle scores
p1 <- plot_x(opt_cut, display_cutpoint = TRUE) + 
   theme_Publication()
p2 <- plot_roc(opt_cut) + 
  theme_Publication()

tiff(file.path(analysis_dir, "plots", "all_shuffled.tiff"), height = 1200, width = 2400, res = 300)
p <- ggarrange(p1, p2, widths = c(1500, 900), height = c(1200, 600), align = "h",
          labels = c("A", "B"),
          ncol = 2, nrow = 1)
p$`1`
dev.off()

```

#run optimal cutpoint by group
```{r}
opt_cut <- cutpointr(meta, telomere_ratio, alt_final, group, metric = sum_sens_spec, 
                     tol_metric = 0.05, break_ties = c, na.rm = T)
summary(opt_cut)
```

#plot by group
```{r fig.height=4, fig.width=6}
#save as PDF
tiff(file.path(analysis_dir, "plots", "all-pbta-by-subgroup.tiff"), height = 1200, width = 1800, res = 300)
plot_metric(opt_cut) +
  theme_Publication()
#invisible(dev.off())
dev.off()
```
#subset and plot - HGAT
```{r}
opt_cut %>%
  filter(subgroup == "HGAT") %>%
  select(optimal_cutpoint, sum_sens_spec) %>% 
  unnest(cols = c(optimal_cutpoint, sum_sens_spec)) %>%
  arrange(-sum_sens_spec)
```

#subset and plot - non-HGAT
```{r}
opt_cut %>%
  filter(subgroup == "non-HGAT") %>%
  select(optimal_cutpoint, sum_sens_spec) %>% 
  unnest(cols = c(optimal_cutpoint, sum_sens_spec)) %>%
  arrange(-sum_sens_spec)
```

#all samples together - cutpoint
```{r}
cp <- cutpointr(meta, telomere_ratio, alt_final, 
                method = maximize_metric, metric = sum_sens_spec, na.rm = T)
summary(cp)
```
# all samples together - plot
```{r all pbta roc, fig.height=4, fig.width=8}
p1 <- plot_x(cp, display_cutpoint = TRUE) + 
   theme_Publication()
p2 <- plot_roc(cp) + 
  theme_Publication()
tiff(file.path(analysis_dir, "plots", "all-pbta.tiff"), height = 1200, width = 2400, res = 300)
p <- ggarrange(p1, p2, widths = c(1500, 900), height = c(1200, 600), align = "h",
          labels = c("A", "B"),
          ncol = 2, nrow = 1)
p$`1`
dev.off()
```

#hgat alone - cutpoint
```{r}
cp <- cutpointr(hgat, telomere_ratio, alt_final,
                method = maximize_metric, metric = sum_sens_spec, na.rm = T)
summary(cp)
```

#hgat alone - plot
```{r roc hgat, fig.height=4, fig.width=8}
tiff(file.path(analysis_dir, "plots", "hgat.tiff"), height = 1200, width = 2400, res = 300)

p1_2 <- plot_x(cp, display_cutpoint = TRUE) + 
   theme_Publication()
p3 <- plot_roc(cp) + 
theme_Publication()

p <- ggarrange(p1_2, p3, widths = c(1500, 900), height = c(1200, 600),
          labels = c("A", "B"),
          ncol = 2, nrow = 1)
p$`1`
invisible(dev.off())
```

#non-hgat alone cutpoint
```{r}
 cp <- cutpointr(non_hgat, telomere_ratio, alt_final, 
                 method = maximize_metric, metric = sum_sens_spec, na.rm = T)
 summary(cp)
```

#non-hgat alone plot
```{r roc non-hgat, fig.height=4, fig.width=8}
tiff(file.path(analysis_dir, "plots", "non-hgat.tiff"), height = 1200, width = 2400, res = 300)

p1_2 <- plot_x(cp, display_cutpoint = TRUE) + 
   theme_Publication()
p3 <- plot_roc(cp) + 
theme_Publication()

p <- ggarrange(p1_2, p3, widths = c(1500, 900), height = c(1200, 600),
          labels = c("C", "D"),
          ncol = 2, nrow = 1)
p$`1`
invisible(dev.off())
```