#col2hex("violetred1")

colors = c("Missense_Mutation" = "#3CB371", 
            "Nonsense_Mutation" = "#000000",
            "Frame_Shift_Del" = "#56B4E9", 
            "Frame_Shift_Ins" = "#FFBBFF", 
            "Splice_Site" = "#F0E442",
            "Splice_Region" = "#F0E442",
            "Translation_Start_Site" = "#191970",
            "Nonstop_Mutation" = "#545454",
            "In_Frame_Del" = "#CAE1FF",
            "In_Frame_Ins" = "#FFE4E1",
            "Stop_Codon_Ins" = "#CC79A7",
            "Start_Codon_Del" = "#56B4E9",
            "Fusion" = "#7B68EE",
            "Multi_Hit_Fusion" = "#CD96CD",
            "Multi_Hit" = "#FF3E96",
            "Del" = "#313695",
            "Amp" = "#c51b7d",
            "Likely Oncogenic" = "#c51b7d",
            "VUS" = "gray")

mut.labels = c("Missense Mutation", 
               "Nonsense Mutation",
               "Frameshift Deletion", 
               "Frameshift Insertion", 
               "Splice Site",
               "Splice Region",
               "Translation Start Site",
               "Nonstop Mutation",
               "Inframe Deletion",
               "Inframe Insertion",
               "Stop Codon Insertion",
               "Start Codon Deletion",
               "RNA Fusion",
               "Multi-Hit RNA Fusion",
               "Multi-Hit",
               "Del",
               "Amp")

