---
title: "TERT,ATRX,DAXX alterations in cohort"
output: html_notebook

params:
  histology_file:
    label: "Cohort specific annotation file"
    value: pbta-histologies.tsv
    input: file
  telomere_ratio:
    label: "Telomere ratio file from merging control_summary.tsv and tumor_summary.tsv"
    value: telomere_940_ratio.tsv
    input: file  

---

```{r echo=FALSE,message=FALSE,warning=FALSE}
set.seed(12345)

root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
library(data.table)
library(tidyverse)

# , subset to PBTA
histology <- read_tsv(file.path(root_dir,"data", params$histology_file), guess_max = 3000)

telomere_ratio <- read_tsv(file.path(root_dir,"analyses","01-alterations_ratio_check", "input",params$telomere_ratio))

consensus_snv <- fread(file.path(root_dir,"data","snv-consensus-plus-hotspots.maf.tsv.gz"),
                       select=c("IMPACT","Hugo_Symbol","Tumor_Sample_Barcode","HGVSp_Short")) %>%
  filter(Tumor_Sample_Barcode %in% histology$Kids_First_Biospecimen_ID) %>%
  unique()

consensus_cnv <- read_tsv(file.path(root_dir,
                                      "data",
                                      "consensus_wgs_plus_cnvkit_wxs.tsv.gz")) %>%
  filter(biospecimen_id %in% histology$Kids_First_Biospecimen_ID)

manta_sv <- read_tsv(file.path(root_dir,
                                      "data",
                                      "pbta-sv-manta.tsv.gz")) %>%
  filter(Kids.First.Biospecimen.ID.Tumor %in% histology$Kids_First_Biospecimen_ID)
```

```{r echo=FALSE,message=FALSE,warning=FALSE}
source(file.path("..","utils","get_alt.R"))

ATRX_alt <- get_alt("ATRX")
DAXX_alt <- get_alt("DAXX")
TERT_alt <- get_alt("TERT")

```

```{r}
# merge snv alterations
merge_ATRX <- ATRX_alt$consensus_snv


if ( !is.null(ATRX_alt$consensus_cnv) ){
  merge_ATRX <- merge_ATRX %>%
    full_join(ATRX_alt$consensus_cnv,by=c("Tumor_Sample_Barcode"="biospecimen_id","Hugo_Symbol"))}

if ( nrow(ATRX_alt$manta_sv) > 0){
  merge_ATRX <- merge_ATRX %>%
    full_join(ATRX_alt$manta_sv,by=c("Tumor_Sample_Barcode"="Kids.First.Biospecimen.ID.Tumor","Hugo_Symbol"))
}

merge_ATRX <- merge_ATRX %>% 
  dplyr::select(-Hugo_Symbol)
#remove NA column - needs fixed
merge_ATRX <- merge_ATRX[,-7]
```


```{r}
# merge snv alterations
merge_DAXX <- DAXX_alt$consensus_snv

if ( !is.null(DAXX_alt$consensus_cnv) ){
  merge_DAXX <- merge_DAXX %>%
    full_join(DAXX_alt$consensus_cnv,by=c("Tumor_Sample_Barcode"="biospecimen_id","Hugo_Symbol"))
}

if ( nrow(DAXX_alt$manta_sv) > 0){
  merge_DAXX <- merge_DAXX %>%
    full_join(DAXX_alt$manta_sv,by=c("Tumor_Sample_Barcode"="Kids.First.Biospecimen.ID.Tumor","Hugo_Symbol"))
}

merge_DAXX <- merge_DAXX %>% dplyr::select(-Hugo_Symbol)

```


```{r}
# get 5'Flank upstream gene variants for TERT - shouold probably combine this with read in snv file above
TERT_promoter_alt <- fread(file.path(
  root_dir,
  "data",
  "snv-consensus-plus-hotspots.maf.tsv.gz"),
  select=c("IMPACT","Hugo_Symbol","Tumor_Sample_Barcode","Existing_variation","Consequence","Reference_Allele","Tumor_Seq_Allele2")) %>% 
  filter(Tumor_Sample_Barcode %in% histology$Kids_First_Biospecimen_ID) %>%
  unique() %>% 
  dplyr::filter(Consequence == "upstream_gene_variant", Hugo_Symbol=="TERT") 

colname<-paste0("TERT_upstream_mut_consensus")
TERT_promoter_alt <- TERT_promoter_alt %>%
  dplyr::select (c("Tumor_Sample_Barcode",
                   "Hugo_Symbol","Existing_variation")) %>%
  # unique so that 1 = mutation exists 0 mutation doesn't exist
  unique() 

if (nrow(TERT_promoter_alt)>0) {
  TERT_promoter_alt <- TERT_promoter_alt %>%
    dplyr::group_by(Tumor_Sample_Barcode, Hugo_Symbol) %>%
    # aggregate mutations
    summarise( !! colname := toString(Existing_variation))
}


# merge snv alterations
merge_TERT <- TERT_alt$consensus_snv %>%
  full_join(TERT_promoter_alt, by=c("Tumor_Sample_Barcode","Hugo_Symbol"))

if ( !is.null(TERT_alt$consensus_cnv) ){
  merge_TERT <- merge_TERT %>%
    full_join(TERT_alt$consensus_cnv,by=c("Tumor_Sample_Barcode"="biospecimen_id","Hugo_Symbol"))}

if ( nrow(TERT_alt$manta_sv) > 0){
  merge_TERT <- merge_TERT %>%
    full_join(TERT_alt$manta_sv,by=c("Tumor_Sample_Barcode"="Kids.First.Biospecimen.ID.Tumor","Hugo_Symbol"))
  }

merge_TERT <- merge_TERT %>% dplyr::select(-Hugo_Symbol)
```

```{r}
final <- histology %>%
  dplyr::filter(experimental_strategy %in% c("WGS"),
                sample_type=="Tumor") %>%
  dplyr::select("Kids_First_Biospecimen_ID","Kids_First_Participant_ID","sample_id") %>%
  left_join(merge_TERT,by=c("Kids_First_Biospecimen_ID"="Tumor_Sample_Barcode")) %>%
  left_join(merge_ATRX,by=c("Kids_First_Biospecimen_ID"="Tumor_Sample_Barcode")) %>%
  left_join(merge_DAXX,by=c("Kids_First_Biospecimen_ID"="Tumor_Sample_Barcode")) %>%
  write_tsv(file.path("..","output","PutativeDriver_ATRX_DAXX_TERT_DNA_alt.tsv"))
```

