---
title: "TP53 HIST1H3B,H3F3A,HIST1H3C alterations in cohort"
output: html_notebook

params:
  histology_file:
    label: "Cohort specific annotation file"
    value: pbta-histologies.tsv
    input: file
  telomere_ratio:
    label: "Telomere ratio file from merging control_summary.tsv and tumor_summary.tsv"
    value: telomere_940_ratio.tsv
    input: file  
  merge_dna_alt:
    label: "Merged files for ATRX,DAXX,TERT DNA alterations"
    value: ../output/PutativeDriver_ATRX_DAXX_TERT_DNA_alt.tsv
    input: file 
  merge_rna_alt:
    label: "Merged FPKM and fusion list for RNA alterations"
    value: ../output/PutativeDriver_ATRTX_DAXX_TERT_RNA_alt.tsv
    input: file   

---

```{r echo=FALSE,message=FALSE,warning=FALSE}
set.seed(12345)

root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))

library(data.table)
library(tidyverse)
library(openxlsx)

# histology
histology <- read_tsv(file.path(root_dir,"data",params$histology_file)) 
# cell-line composition 
cell_line <- read_tsv("../input/cell-line-composition.tsv") %>% 
  dplyr::select(Kids_First_Biospecimen_ID ,cell_line_composition)

# telomere ratio
telomere_ratio <- read_tsv(file.path(root_dir,
                                     "analyses",
                                     "01-alterations_ratio_check", 
                                     "input", 
                                     params$telomere_ratio)) 

# DNA alterations
merge_dna_ATRX_DAXX_TERT <- read_tsv(file.path(params$merge_dna_alt)) %>%
  left_join(cell_line)

# RNA alterations
merged_rna_ATRX_DAXX_TERT <- read_tsv(file.path(params$merge_rna_alt))  %>%
  left_join(cell_line)


```


```{r}

all_alterations <- merge_dna_ATRX_DAXX_TERT %>%
  left_join(merged_rna_ATRX_DAXX_TERT,suffix=c("_DNA","_RNA"),by=c("Kids_First_Participant_ID","sample_id","cell_line_composition")) %>%
  dplyr::select("Kids_First_Participant_ID","Kids_First_Biospecimen_ID_DNA","Kids_First_Biospecimen_ID_RNA",everything()) %>%
  dplyr::mutate(
    "alterations_ATRX"=case_when(
    !is.na(ATRX_MOD_HIGH_mut_consensus) | 
      !is.na(ATRX_loss_consensus) |
      !is.na(ATRX_gain_consensus) ~ "ATRX_mut",
    TRUE ~ NA_character_
  ),"alterations_DAXX"=case_when(
      !is.na(DAXX_loss_consensus) |
      !is.na(DAXX_gain_consensus)  ~ "DAXX_mut",
      TRUE ~ NA_character_
  ),"alterations_TERT"=case_when(
    !is.na(TERT_MOD_HIGH_mut_consensus) | 
      !is.na(TERT_upstream_mut_consensus) |
      !is.na(TERT_amplification_consensus) | 
      !is.na(TERT_gain_consensus) |
      !is.na(TERT_loss_consensus) ~ "TERT_mut",
    TRUE ~ NA_character_
  )) 

```

```{r}


all_alterations[all_alterations == 0] <- NA

all_alterations <- all_alterations %>% 
  dplyr::mutate("defining_alt" = 
                  case_when(
                    !is.na(alterations_TERT) &
                      !is.na(alterations_DAXX) & 
                      !is.na(alterations_ATRX) ~ paste(alterations_TERT,alterations_DAXX,alterations_ATRX),
                !is.na(alterations_DAXX) & 
                  !is.na(alterations_ATRX) ~ paste(alterations_DAXX,alterations_ATRX),
                !is.na(alterations_TERT) & 
                  !is.na(alterations_ATRX) ~ paste(alterations_TERT,alterations_ATRX),
                !is.na(alterations_TERT) & 
                  !is.na(alterations_DAXX) ~ paste(alterations_TERT,alterations_DAXX),
                !is.na(alterations_ATRX) ~ alterations_ATRX,
                !is.na(alterations_DAXX) ~ alterations_DAXX,
                !is.na(alterations_TERT) ~ alterations_TERT,
                TRUE ~ "no SNV/CNV alt"
                ) ) %>%
  dplyr::select(-alterations_ATRX,
                - alterations_DAXX,
                - alterations_TERT)
                  
```


```{r}
all_alterations_ratio <- all_alterations %>%
  left_join(telomere_ratio,by = c("Kids_First_Participant_ID",
                                "Kids_First_Biospecimen_ID_DNA" = "Kids_First_Biospecimen_ID_tumor")) %>%
  dplyr::mutate(ratio = log2(ratio)) %>%
  dplyr::rename(telomere_ratio=ratio) %>%
  # since there are NA in RNA Ids in some rows 
  # using only WGS DNA which is used in telomerehunter to match to histology
  full_join(histology[which(
      histology$experimental_strategy=="WGS" &
        histology$sample_type== "Tumor"),],
            by=c("Kids_First_Biospecimen_ID_DNA"="Kids_First_Biospecimen_ID",
            "Kids_First_Participant_ID","sample_id")) 


all_alterations_ratio %>%
  dplyr::select(-defining_alt) %>%
  write_tsv(file.path("../output/all_alterations_ATRX_DAXX_TERT.tsv"))


```